---
title: "SDG Analytics Dashboard"
author: "Tallen Vidal"
format: 
  dashboard:
    orientation: rows
---

```{r, echo = FALSE}
library(tidycensus)
library(tidyverse)
library(plotly)
library(dplyr)
library(here)
library(janitor)
library(plotly)
library(rnaturalearth)
library(leaflet)
library(sf)
library(vembedr)
library(naniar) # analyzes missing data
library(ggcorrplot)
library(ggpubr)
library(cluster) 
library(randomForest) # runs random forest algorithm
library(missRanger) # imputes data through with random forest method
library(factoextra) # visualizes clusters
library(pdp)

```

```{, echo = FALSE}
sdr_data <- read_csv(here("data/SDR-2023-Data.csv"))

sdr_data_clean <- sdr_data %>% 
  clean_names()
```

```{r}
install.packages("rnaturalearthdata")
```

## Row 1

```{r}
goal_1_histogram <- ggplot(sdr_data_clean, aes(x = goal_1_score, fill=regions_used_for_the_sdr)) +
  geom_histogram() +
  theme_minimal() +
  scale_fill_viridis_d(option="mako") +
  labs(title = "Distributions of SDG 1 Scores",
       x = "SDG 1 Score",
       y = "Number of Countries",
       fill = "Region")

ggplotly(goal_1_histogram)
```

## Row 2 {.tabset}

```{r, echo =}
sdr_data_normalized_scores <- sdr_data_clean %>% 
  select(country, contains("normalized_score"))  

sum(is.na(sdr_data_normalized_scores))
sdr_data_normalized_scores_longer <- sdr_data_normalized_scores %>% 
  pivot_longer(cols = !country)
missing_data_by_country <- sdr_data_normalized_scores_longer %>%
 group_by(country) %>%
 miss_var_summary() %>% 
 arrange(desc(pct_miss))

completely_na_countries  <- missing_data_by_country$country[missing_data_by_country$pct_miss == 100]

sdr_data_normalized_scores_no_na_countries <- sdr_data_normalized_scores %>% 
  filter(!country %in% completely_na_countries)

sdr_data_normalized_scores_less_na <- sdr_data_normalized_scores_no_na_countries %>%
  select(where(~ sum(is.na(.))/length(.) <= 0.2))

sdr_data_imputed <- missRanger(sdr_data_normalized_scores_less_na)
```

```{r}
SDG_1_Indicators_Scatterplot<-ggplot(data = sdr_data_imputed, aes(x= normalized_score_sdg1_wpc, y = normalized_score_sdg1_lmicpov, color=country)) +
  geom_point()+
  theme_minimal() +
  scale_fill_viridis_d() +
  labs(title = "Distributions of SDG 1 Indicator Scores",
       x = "World Petroleum Congress Score",
       y = "Low-Middle Income Country Score",
       fill = "Country")

ggplotly(SDG_1_Indicators_Scatterplot)


```





```{r}

```

